import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { City } from '../src/world/City.js';
import { SKY } from '../src/world/sky.js';

const renderer = new THREE.WebGLRenderer({ antialias: true, preserveDrawingBuffer: true });
renderer.setPixelRatio(Math.min(2, window.devicePixelRatio));
renderer.setSize(innerWidth, innerHeight);
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFShadowMap;
renderer.toneMapping = THREE.NeutralToneMapping;
document.body.appendChild(renderer.domElement);
const scene = new THREE.Scene();
scene.fog = new THREE.Fog(SKY.haze, 120, 700);
const hemi = new THREE.HemisphereLight(0xd8ecff, 0xb8a58c, 1.25);
scene.add(hemi);
const sun = new THREE.DirectionalLight(0xfff0dc, 2.4);
sun.position.copy(SKY.sunDir).multiplyScalar(200);
sun.castShadow = true;
sun.shadow.mapSize.set(4096, 4096);
const sc = sun.shadow.camera;
sc.left = -230; sc.right = 230; sc.top = 230; sc.bottom = -230; sc.near = 1; sc.far = 600;
sun.shadow.bias = -0.0005;
scene.add(sun);
scene.add(sun.target);
const t0 = performance.now();
const city = new City(scene);
const buildMs = performance.now() - t0;
const pm = new THREE.PMREMGenerator(renderer);
const envScene = new THREE.Scene();
envScene.add(city.sky.clone());
scene.environment = pm.fromScene(envScene, 0.02).texture;
const camera = new THREE.PerspectiveCamera(55, innerWidth / innerHeight, 0.5, 3000);
camera.position.set(-60, 140, 260);
const controls = new OrbitControls(camera, renderer.domElement);
controls.target.set(0, 0, 0);
let last = performance.now();
function frame(now) {
  const dt = Math.min(0.05, (now - last) / 1000); last = now;
  city.update(dt, camera);
  controls.update();
  renderer.render(scene, camera);
  document.getElementById('info').textContent = `build ${buildMs.toFixed(0)}ms  calls ${renderer.info.render.calls}  tris ${renderer.info.render.triangles}  colliders ${city.col.list.length}  dest ${city.destinations.length}`;
  requestAnimationFrame(frame);
}
requestAnimationFrame(frame);
addEventListener('resize', () => { renderer.setSize(innerWidth, innerHeight); camera.aspect = innerWidth / innerHeight; camera.updateProjectionMatrix(); });
window.__cam = (px, py, pz, tx, ty, tz) => { camera.position.set(px, py, pz); controls.target.set(tx, ty, tz); controls.update(); };
window.__shot = async (name) => { renderer.render(scene, camera); const url = renderer.domElement.toDataURL('image/png'); const r = await fetch('/__shot?name=' + name, { method: 'POST', body: url }); return r.ok; };
window.__city = city;
